### ISSUE TITLE
L3VNF Example On Ubuntu 18.04

### ISSUE THREAD

**Issue by rider8581** [networkedsystemsIITB/libVNF#1]
Good day,

Thank you for sharing this awesome project.

I was trying to run L3VNF on ubuntu18.04 and faced some issues.
https://github.com/networkedsystemsIITB/libVNF/tree/release-socc/examples/LB

So first of all, I am trying to install netmap but facing errors while configure qemu.

https://github.com/networkedsystemsIITB/Modified_mTCP/blob/master/mTCP_over_Netmap/docs/netmap_docs/user_manual.pdf
I am trying to follow this document (step 1-4) but in step 1.2, cannot configure qemu

When I run this:
./configure --target-list=x86_64-softmmu --python=python2 --enable-kvm --enable-vhost-net --disable-werror --enable-netmap --enable-ptnetmap --extra-cflags=-I/home/rider/L3VNF/netmap/sys
I am facing this error:
![image](https://user-images.githubusercontent.com/52605718/120829757-595a8880-c590-11eb-8c78-606fa6c36601.png)

So I try this:
./configure --target-list=x86_64-softmmu --python=python2 --enable-kvm --enable-vhost-net --disable-werror --enable-netmap --extra-cflags=-I/home/rider/L3VNF/netmap/sys
facing this:
![image](https://user-images.githubusercontent.com/52605718/120829829-7000df80-c590-11eb-9171-90763613881e.png)

I checked I installed libglib2.0-dev.
![image](https://user-images.githubusercontent.com/52605718/120882501-ea6e4580-c60a-11eb-86ef-fcb224a08e90.png)

Not sure, what the issue is.

Please help me.

It would be great if there is more practical guide to run L3VNF example on ubuntu18.04.

Thank you so much.

**Comment by ppnaik1890** [comment]
Hi,
Thank you for your interest.
ptnetmap setup is required for a VM based setup. In case that is not required, you can just follow the steps below:

``` 
git clone https://github.com/luigirizzo/netmap.git
cd netmap
git checkout 21227d47ae995812412d1de22855c7fa8260f53a 
cd LINUX/
	# download linux source /home/turing_05/linux-4.15 beforehand. Please check net on how to download 
./configure --no-drivers=mlx5 --enable-ptnetmap --enable-pipe --enable-monitor --enable-vale --drivers=i40e --kernel-sources=/home/turing_05/linux-4.15 
(in case your NIC is mellanox, remove the --no-drivers=mlx5 from above)
#in case 1G NIC is to be used and igb not found warning comes as we got for igb in 4.15-72 kernel, give a different igb version and check. We used the following command:
sudo make clean && sudo make distclean && ./configure --no-drivers=mlx5 --enable-ptnetmap --enable-pipe --enable-monitor --enable-vale --drivers=igb --select-version=igb:5.3.5.18
sudo make
sudo make install
```
These steps are enough for netmap setup, and you do not need the mTCP setup for L3 VNF. Hope this helps.

**Comment by rider8581** [comment]
Thank you so much for your kind reply.
Btw, do you have any practical guide to run L3VNF example on ubuntu18.04?

**Comment by ppnaik1890** [comment]
In case you are interested in libvnf based L3 VNF, you can follow the steps above and the setup in libVNF readme.
Are you looking for something else? like running L3VNF without LibVNF over kernel or netmap network stack?

**Comment by rider8581** [comment]
I am sorry, I meant, I want to run this example:
https://github.com/networkedsystemsIITB/libVNF/tree/release-socc/examples/LB

**Comment by ppnaik1890** [comment]
Ideally, the steps to follow should be:
1. libboost-all-dev install
2. [steps here](https://github.com/networkedsystemsIITB/libVNF/issues/1#issuecomment-855404726)
3. Make changes in Cmakefile according to [here](https://github.com/networkedsystemsIITB/libVNF/tree/release-socc/examples/LB#preparation)
3. [steps here](https://github.com/networkedsystemsIITB/libVNF/tree/release-socc/examples/LB#preparation)
4. We have tested the loadgen with abc example (you can run the abc example over kernel stack). 
Hope this helps. Thanks.

**Comment by rider8581** [comment]
Thank you for your help, let me try this.

**Comment by rider8581** [comment]
Hi, hope you are doing well.

I tried to follow your guide and faced some issues:

git clone https://github.com/luigirizzo/netmap.git
cd netmap
git checkout 21227d47ae995812412d1de22855c7fa8260f53a 
cd LINUX/

I am following this step but it is making errors when I try checkout.
![image](https://user-images.githubusercontent.com/52605718/121107120-f2f89300-c839-11eb-9b14-c492e030a81b.png)
Maybe it is related to branch.

When I skip this error and use the latest version of netmap, it gives error while compilation.

sudo make clean && sudo make distclean && ./configure --no-drivers=mlx5 --enable-ptnetmap --enable-pipe --enable-monitor --enable-vale --drivers=igb --select-version=igb:5.3.5.18
sudo make

![image](https://user-images.githubusercontent.com/52605718/121109047-651ea700-c83d-11eb-9749-0a65e6d8c211.png)

I guess, it is because I failed with checkout and it is using the latest version of netmap.

Please help me. thank you.

**Comment by ppnaik1890** [comment]
We did not face this issue. Might be a kernel version issue. I see you have removed the kernel source param from the command. Can you download the kernel source corresponding to your kernel version and pass it as parameter to `configure `and try once.

**Comment by rider8581** [comment]
Could you let me know what kernel version you are using?

**Comment by ppnaik1890** [comment]
The kernel version is `5.0.0-37-generic`

**Comment by rider8581** [comment]
I built L3VNF and now I am trying to build backend kernel module for LB example.
https://github.com/networkedsystemsIITB/libVNF/blob/release-socc/examples/LB/backend_kernel_module/README.md
However, when I try to compile, it gives the following error:
![image](https://user-images.githubusercontent.com/52605718/123117232-6c75b100-d3f6-11eb-88cf-1d1a2d4f1b11.png)

Hopefully it depends on kernel version (my version is 4.15.0-144-generic).
![image](https://user-images.githubusercontent.com/52605718/123117447-9af38c00-d3f6-11eb-8907-bb27992d30e2.png)

Would you kindly guide me?

Thank you.

**Comment by ppnaik1890** [comment]
Hi, Yes this definitely looks like kernel version issue. Haven't tested the code for 4.15 kernel version though. But for a newer version the attached code worked
 https://github.com/ppnaik1890/Trialwork/blob/main/lb_module.c
 In case this too doesnt work, you will have to look through your kernel version and look for correct format for passing kobject

**Comment by rider8581** [comment]
You are right.
It has been built successfully after I update the interfaces of function pointers for my kernel version.
However, when I run load_balancer, it gives me the following error:
![image](https://user-images.githubusercontent.com/52605718/123195399-f7899200-d45c-11eb-840a-d34964305016.png)
I checked the /dev/ directory but there is no devices related to netmap.
I suppose after I install netmap, I need to create some device?
Please guide me, (I sincerely appreciate your kind help.)
https://github.com/networkedsystemsIITB/libVNF/issues/1#issuecomment-855404726
Following your this guide, I was able to build and install netmap.

**Comment by ppnaik1890** [comment]
Yes. U need to start the netmap module and point ur interface to use its driver. The replace the interface name and IP and netmask and path to netmap folder in the below script and hopefully that should fix this issue. In case you are using 40GB NIC uncomment the corresponding line:
```
NIC=ens0
IP=169.254.9.84
NETMASK=255.255.0.0
NUMBUFS=1024
sudo rmmod i40e
sudo insmod /home/dummy/netmap/LINUX/netmap.ko
modprobe vxlan
#sudo insmod /home/dummy/netmap/LINUX/i40e/i40e.ko
ethtool -G $NIC rx $NUMBUFS tx $NUMBUFS
ifconfig $NIC $IP netmask $NETMASK
ethtool -K $NIC tx off rx off gso off tso off gro off lro off
ethtool -N $NIC rx-flow-hash tcp4 sdfn
#ethtool -N $NIC rx-flow-hash udp4 sdfn
sudo insmod /home/dummy/netmap/LINUX/igb/igb.ko
sudo ifconfig ens0 up
```

**Comment by rider8581** [comment]
https://github.com/networkedsystemsIITB/libVNF/blob/release-socc/examples/LB/backend_kernel_module/lb_module.c
Would you kindly guide me how I can add the log lines to this kernel module and track?
There is a function printk, but not sure where it outputs the log.
I am trying to understand how this kernel module works but couldn't understand since it doesn't have related documentation.
That is why I am trying to add log lines and track.
Please guide me, thank you.

**Comment by ppnaik1890** [comment]
the printk get printed in `dmesg` or `syslog` since it is a kernel module. U can add more such statement based on the existing printk statement. Hope this helps. For better viewing do `sudo dmesg -C` before starting the module to get just the logs from the module and remove other system logs. Hope this helps.

**Comment by rider8581** [comment]
![image](https://user-images.githubusercontent.com/52605718/124114115-07871000-da21-11eb-918d-5fef08531b25.png)
I enabled these lines and add the lines in hook_func_in function to check the incomming packets but it didn't catch the packets incoming from the client, "a".
I dumped the packet stream and analyzed with wireshark.
![image](https://user-images.githubusercontent.com/52605718/124114333-4d43d880-da21-11eb-9eb9-1c2051a56963.png)
As I checked, the server replied to the ARP request from the client with the MAC address of "00:aa:bb:cc:dd:04".
This is not the MAC address of my real nic but it comes from libVNF kernel l3 implementation.
I think that is why hook in function doesn't catch the packet.
Can you give me some comment on this issue?

**Comment by ppnaik1890** [comment]
Ohh. Can you confirm you did the changes mentioned here:
https://github.com/networkedsystemsIITB/libVNF/blob/release-socc/examples/LB/backend_kernel_module/README.md

**Comment by rider8581** [comment]
![image](https://user-images.githubusercontent.com/52605718/124149748-be958280-da45-11eb-8321-32027d482146.png)
yes, I put my server's IP here.

**Comment by ppnaik1890** [comment]
And just to confirm you have set the below too. 
```
In load_balancer.cpp do the following changes:
In line 243 change the first parameter to your interface name("eth5" in our case) and the second parameter to your IP address.
In line 248 change the string assigned to to_send variable to the IP address of your backend VNF.
You can add more backends by doing more setData(and incrementing its fourth parameter) and backend_count++ after each setData.
```
Also to confirm your `Load balancer runs over netmap` and `backend (i.e. B runs over kernel)` and your B runs on port `5000`

For better understanding can you please help me with IPs and MAC's of A, LB and B. Thanks!

**Comment by rider8581** [comment]
![image](https://user-images.githubusercontent.com/52605718/124155538-6eb9ba00-da4b-11eb-9fc2-3bc511cdcae4.png)
This is for LB
![image](https://user-images.githubusercontent.com/52605718/124155586-7f6a3000-da4b-11eb-8cd4-dc4aea6fc692.png)
This is for A.
I haven't activated B yet.
LB is running on netmap and backend. I added the log lines to load_balancer.cpp and checked it accepts ARP requests and reply. But not receiving TCP stream.
I have following questions:
1. Is it possible to activate B on the same machine with A but with different port like 6000?
2. LB's ARP response was "00:aa:bb:cc:dd:04". Is this correct or should it return it's adapter's real MAC?
3. When LB runs over netmap and backend, does the PING from A to LB work?

**Comment by ppnaik1890** [comment]
You need to start B since you see a SYN has been received. It will only be handled when you start B at port 5000. For clarity B is the backend. 
I have not done A and B both on single machine with LB. (May not work since we have the kernel module modify packet headers). 
To give you context of what this LB does. Your A sends requests to LB's IP (A assumes this as the server's IP). LB modifies the IP to be backend IP so the request reaches B via LB. B processes it and when replying back the kernel module modifies the source IP to be the LB IP so that A feels the packet (reply) is coming from same IP it sends requests too. This is similar to how direct return server based LB work. 
Also, all the above assumes you will start B over kernel stack that's when kernel module will work. If you will run B over mTCP you will need to follow the other steps we used. 
We have handled arp in the LB code so mostly shouldn't be a problem. I do not see the MAC address mentioned above in the code so may be it is correct (if you have the IP set to a machine with netmap or DPDK and have set this IP and MAC by some previous setting). Hope this helps.

**Comment by rider8581** [comment]
So the packet flows as following:
![image](https://user-images.githubusercontent.com/52605718/125065223-6c1c1d80-e066-11eb-93cc-720b1f125541.png)
1, A sends packets to LB
2. LB modifies the dst IP to B's IP and send to B.
3. B processes and send a reply to A. The kernel module of B modifies src IP to LB's IP.

Am I right?

**Comment by ppnaik1890** [comment]
Yes correct.

**Comment by rider8581** [comment]
![image](https://user-images.githubusercontent.com/52605718/125081544-fbcbc700-e07a-11eb-92b6-e4494bc52a2f.png)
For multiple backends, is the above diagram correct?

**Comment by ppnaik1890** [comment]
Yes

**Comment by rider8581** [comment]
So netmap is just for kernel module on B machine and it wont be needed on LB machine?

**Comment by ppnaik1890** [comment]
Ahh actually no. The LB is over netmap. Assuming our previous conversation B is over kernel and needs the kernel module to change the source IP to LB IP. For clarity the kernel module is not the LB code. The kernel module needs to just run on B machine. The LB code (load_balancer.cpp) runs over netmap. 
(In case you want to run the B over mTCP/netmap stack instead of kernel you need to modify mTCP was suggested [here](https://github.com/networkedsystemsIITB/Modified_mTCP/tree/master/mtcp_when_using_lb)).

Hope this helps.

**Comment by rider8581** [comment]
How did you run B? Did you use b in abc example? I saw the b of abc example uses libVNF/mtcp. Did you use it?

**Comment by ppnaik1890** [comment]
I have tested both the options. B running over libVNF (using mTCP) and B over libVNF (using kernel network stack).

**Comment by rider8581** [comment]
![image](https://user-images.githubusercontent.com/52605718/127740464-5b3e34aa-a26b-4119-b684-cf6111291bd1.png)
the kernel module on B replaces the src IP with the LB's IP, But I think it doesn't replace the MAC address,
Do you think if it is okay for A to receive B's reply correctly?
He sent the packet to LB's MAC address but the reply is coming from B's MAC address. Does this work?
I am testing but it is not receiving packets.
![image](https://user-images.githubusercontent.com/52605718/127740780-20ed6d16-8d65-4395-83ee-bfe4a63ced30.png)
This is A's output.

**Comment by rider8581** [comment]
![image](https://user-images.githubusercontent.com/52605718/127741071-427db31d-393e-4db7-91b5-1a3f2c130e56.png)
A: 192.168.126.136
B: 192.168.126.137:5000
LB: 192.168.126.138:5000
The above diagram is the packet stream that has been captured on A.
LB is replying with data but A cannot read it.

Would you please check this for me?
![image](https://user-images.githubusercontent.com/52605718/127741247-df23e255-4dcf-4e45-bff6-fd4a3da0d880.png)

**Comment by ppnaik1890** [comment]
Hi,
Looks like the TCP connection is happening correctly. That is the TCP 3way handshake (SYN-SYN/ACK-ACK) look fine. If its was a MAC address issue this too would not have worked. Two things to try but not sure if that would solve this:
1. May be once check is you can try doing `echo 1 > /proc/sys/net/ipv4/ip_forward`. on B.
2. Can you once check if A-> B directly that is giving server IP as 192.168.126.137:5000 on A side works fine. If that works fine do not see a reason why this is failing.

**Comment by rider8581** [comment]
Thank you for your kind reply.
1. I tried it but not working.
2. Yeah, when I disable the kernel module on B and connect A directly to B, it is working fine.
![image](https://user-images.githubusercontent.com/52605718/127757549-b58042a5-9755-41f4-9ffd-54d956259bab.png)
As you mentioned, A is not receiving correctly the data packets only when there is LB. Not sure why. Are there any way to debug this issue?

**Comment by ppnaik1890** [comment]
So the packets do reach A NIC but not the application (socket drops the packet). Can you once try ip_forward on A. Need to debug this issue. Also, once check if they are some IP table rules blocking it at A.

**Comment by rider8581** [comment]
I tried to ip_forward on but not working, As you mentioned, it is receiving [SYN, ACK] from B but not receiving [PSH, ACK] with data.
So I don't think it is related to IP table.
Are there any way to debug this issue?
![image](https://user-images.githubusercontent.com/52605718/127761667-c55317da-0cb4-4221-9451-ad7886f03d06.png)

**Comment by rider8581** [comment]
I think the kernel module on B has issues.
A: 192.168.126.136
B: 192.168.126.137:5000
LB: 192.168.126.138:5000
So in this architecture, I did the following test:
- Disable LB
- Set the IP replacement on B's kernel module with B's IP "192.168.126.137". So the kernel module activated but it will put B's IP.
- Let A directly connect to B
![image](https://user-images.githubusercontent.com/52605718/127894456-419bd513-36a3-4f79-a380-877e69c892b8.png)
In this case, the same error happened on A.
So I think the error is related to kernel module.
In lb_module.c, I changed only few lines for compile on my ubuntu kernel version:
![image](https://user-images.githubusercontent.com/52605718/127894836-91402153-4a44-40e4-93dd-f62d4d53a06b.png)
![image](https://user-images.githubusercontent.com/52605718/127894881-8144821c-6f21-4fa8-9cf7-9cc4092d3e65.png)
![image](https://user-images.githubusercontent.com/52605718/127894939-42279df8-3e63-4485-99be-59f4c32e2a30.png)
![image](https://user-images.githubusercontent.com/52605718/127894985-6f3f5199-e758-4c21-8309-4376055f7f4e.png)
![image](https://user-images.githubusercontent.com/52605718/127895055-9d75c3ef-bb1a-4bf8-9d96-ab5418984472.png)
![image](https://user-images.githubusercontent.com/52605718/127895091-e083f729-8f2a-468c-85b7-6eae322e5b79.png)
![image](https://user-images.githubusercontent.com/52605718/127895132-33cdbe3e-55f7-402d-9e15-5b97d04756a5.png)
Do you have any idea of this issue? Or would you kindly let me know your os/kernel version for B?

**Comment by rider8581** [comment]
https://drive.google.com/drive/folders/1695j2Y5DSrXo1Vu06Z-7VoPKcPhYUII0?usp=sharing
I have uploaded the packet dump files and lb_module.c
Would you please check these for me?
Thank you so much.

**Comment by rider8581** [comment]
Hi, I suppose you are busy.
Anyway, I managed to figure out the issue.
The issue was because of the kernel version of B machine.
I was using 5.3.0-47-generic but I downgraded it to 5.0.0-37-generic which you suggested and it is working fine now.
lb_module.c is not working in the kernel version of 5.3.0-47-generic. especially the following part is not working.
![image](https://user-images.githubusercontent.com/52605718/128022493-b52bee40-035b-4387-b458-f797817f6997.png)
I am not sure what line 682 does but I think it is related to the issue.
Hope my feedback would be helpful to you as a piece of reference.
I sincerely appreciate all your kind comments and attention.
Thank you.

**Comment by ppnaik1890** [comment]
Hi,
Apologies for missing all the comments. Yes since its a kernel module new versions may have different parameters constraints to get it working. I am really glad you got this to work! Thanks for using libVNF!

**Comment by rider8581** [comment]
Hi there,
Hope you are doing well.
While checking the source of kernel_l3_impl, I found something strange.
The core.cpp of kernel_bypass_impl and kernel_impl are multi-threaded but I think kernel_l3_impl is not.
In kernelbypass and kernel mode, "startEventLoop" function creates the number of threads for packet I/O.
But in L3 mode, I found "startEventLoop" function is single threaded.
So as I understood, even I set the multi-cores in "initLibvnf" function, it won't be multi-threaded.
Would you give me some guidance on this issue?
